HOSTS:
  ubuntu-server-14.04-amd64:
    roles:
      - master
    platform: ubuntu-14.04-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/ubuntu-14.04-64-nocm
    hypervisor: vagrant
CONFIG:
  type: foss
  log_level: debug
# HOSTS:
#   centos-server-70-x64:
#     roles:
#       - master
#     platform: el-7-x86_64
#     box: puppetlabs/centos-7.0-64-nocm
#     box_url: https://vagrantcloud.com/puppetlabs/centos-7.0-64-nocm
#     hypervisor: vagrant
# CONFIG:
#   log_level: debug
#   type: foss
